set_property PACKAGE_PIN E1 [get_ports {ADC_A_IN[0]}]
set_property PACKAGE_PIN E2 [get_ports {ADC_A_IN[1]}]
set_property PACKAGE_PIN D1 [get_ports {ADC_A_IN[2]}]
set_property PACKAGE_PIN D2 [get_ports {ADC_A_IN[3]}]
set_property PACKAGE_PIN C1 [get_ports {ADC_A_IN[4]}]
set_property PACKAGE_PIN B1 [get_ports {ADC_A_IN[5]}]
set_property PACKAGE_PIN B2 [get_ports {ADC_A_IN[6]}]
set_property PACKAGE_PIN A2 [get_ports {ADC_A_IN[7]}]
set_property PACKAGE_PIN F4 [get_ports {ADC_A_IN[8]}]
set_property PACKAGE_PIN D4 [get_ports {ADC_A_IN[9]}]
set_property PACKAGE_PIN C4 [get_ports {ADC_A_IN[10]}]
set_property PACKAGE_PIN C5 [get_ports {ADC_A_IN[11]}]
set_property PACKAGE_PIN B3 [get_ports {ADC_A_IN[12]}]
set_property PACKAGE_PIN B4 [get_ports {ADC_A_IN[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_A_IN[13]}]


set_property PACKAGE_PIN M1 [get_ports {ADC_B_IN[0]}]
set_property PACKAGE_PIN L1 [get_ports {ADC_B_IN[1]}]
set_property PACKAGE_PIN K1 [get_ports {ADC_B_IN[2]}]
set_property PACKAGE_PIN K2 [get_ports {ADC_B_IN[3]}]
set_property PACKAGE_PIN J1 [get_ports {ADC_B_IN[4]}]
set_property PACKAGE_PIN J2 [get_ports {ADC_B_IN[5]}]
set_property PACKAGE_PIN H2 [get_ports {ADC_B_IN[6]}]
set_property PACKAGE_PIN F1 [get_ports {ADC_B_IN[7]}]
set_property PACKAGE_PIN K3 [get_ports {ADC_B_IN[8]}]
set_property PACKAGE_PIN J3 [get_ports {ADC_B_IN[9]}]
set_property PACKAGE_PIN J4 [get_ports {ADC_B_IN[10]}]
set_property PACKAGE_PIN H3 [get_ports {ADC_B_IN[11]}]
set_property PACKAGE_PIN H4 [get_ports {ADC_B_IN[12]}]
set_property PACKAGE_PIN G4 [get_ports {ADC_B_IN[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_B_IN[13]}]


set_property PACKAGE_PIN A4 [get_ports SHND_ADC_B]
set_property PACKAGE_PIN M4 [get_ports SHND_ADC_A]
set_property PACKAGE_PIN A3 [get_ports OE_ADC_B]
set_property PACKAGE_PIN F2 [get_ports OE_ADC_A]
set_property PACKAGE_PIN G1 [get_ports CLK_TO_ADC_B]
set_property PACKAGE_PIN H1 [get_ports CLK_TO_ADC_A]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_TO_ADC_B]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_TO_ADC_A]


set_property PACKAGE_PIN A13 [get_ports clk_100]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100]

set_property PACKAGE_PIN C10 [get_ports boot_sw]
set_property IOSTANDARD LVCMOS33 [get_ports boot_sw]
set_property PACKAGE_PIN B12 [get_ports boot_led]
set_property IOSTANDARD LVCMOS33 [get_ports boot_led]

set_property PACKAGE_PIN B14 [get_ports {led_0[0]}]
set_property PACKAGE_PIN B13 [get_ports {led_1[0]}]

set_property PACKAGE_PIN D7 [get_ports lemo_a]
set_property PACKAGE_PIN B6 [get_ports lemo_b]
set_property PACKAGE_PIN D8 [get_ports lemo_dir_a]
set_property PACKAGE_PIN C7 [get_ports lemo_dir_b]
set_property PACKAGE_PIN C6 [get_ports lemo_oe]

set_property PACKAGE_PIN D9 [get_ports sw1]

set_property PACKAGE_PIN A5 [get_ports {gpio[0]}]
set_property PACKAGE_PIN A6 [get_ports {gpio[1]}]
set_property PACKAGE_PIN A8 [get_ports {gpio[2]}]
set_property PACKAGE_PIN C8 [get_ports {gpio[3]}]
set_property PACKAGE_PIN A9 [get_ports {gpio[4]}]
set_property PACKAGE_PIN A10 [get_ports {gpio[5]}]
set_property PACKAGE_PIN B10 [get_ports {gpio[6]}]
set_property PACKAGE_PIN C9 [get_ports {gpio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio[0]}]





set_property IOSTANDARD LVCMOS33 [get_ports {led_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports lemo_a]
set_property IOSTANDARD LVCMOS33 [get_ports lemo_b]
set_property IOSTANDARD LVCMOS33 [get_ports lemo_dir_a]
set_property IOSTANDARD LVCMOS33 [get_ports lemo_dir_b]
set_property IOSTANDARD LVCMOS33 [get_ports lemo_oe]
set_property IOSTANDARD LVCMOS33 [get_ports OE_ADC_A]
set_property IOSTANDARD LVCMOS33 [get_ports OE_ADC_B]

set_property -dict {PACKAGE_PIN N7 IOSTANDARD LVCMOS33} [get_ports {FTDI_ADBUS[0]}]
set_property -dict {PACKAGE_PIN M7 IOSTANDARD LVCMOS33} [get_ports {FTDI_ADBUS[1]}]
set_property -dict {PACKAGE_PIN M8 IOSTANDARD LVCMOS33} [get_ports {FTDI_ADBUS[2]}]
set_property -dict {PACKAGE_PIN N8 IOSTANDARD LVCMOS33} [get_ports {FTDI_ADBUS[3]}]
set_property -dict {PACKAGE_PIN P7 IOSTANDARD LVCMOS33} [get_ports {FTDI_ADBUS[4]}]
set_property -dict {PACKAGE_PIN L10 IOSTANDARD LVCMOS33} [get_ports {FTDI_ADBUS[5]}]
set_property -dict {PACKAGE_PIN N9 IOSTANDARD LVCMOS33} [get_ports {FTDI_ADBUS[6]}]
set_property -dict {PACKAGE_PIN P10 IOSTANDARD LVCMOS33} [get_ports {FTDI_ADBUS[7]}]
set_property -dict {PACKAGE_PIN P11 IOSTANDARD LVCMOS33} [get_ports FTDI_RXFN]
set_property -dict {PACKAGE_PIN R12 IOSTANDARD LVCMOS33} [get_ports FTDI_TXEN]
set_property -dict {PACKAGE_PIN R11 IOSTANDARD LVCMOS33} [get_ports FTDI_RDN]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports FTDI_TXN]
set_property -dict {PACKAGE_PIN R9 IOSTANDARD LVCMOS33} [get_ports FTDI_SIWU]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports FTDI_CLK]
set_property -dict {PACKAGE_PIN R8 IOSTANDARD LVCMOS33} [get_ports FTDI_OEN]

set_property PACKAGE_PIN L15 [get_ports IIC_0_scl]
set_property PACKAGE_PIN J15 [get_ports IIC_0_sda]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_scl]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_sda]

create_clock -period 16.670 -name FTDI_CLK -waveform {0.000 8.335} [get_ports FTDI_CLK]

set_output_delay -clock [get_clocks FTDI_CLK] -max 5.500 [get_ports {{FTDI_ADBUS[0]} {FTDI_ADBUS[1]} {FTDI_ADBUS[2]} {FTDI_ADBUS[3]} {FTDI_ADBUS[4]} {FTDI_ADBUS[5]} {FTDI_ADBUS[6]} {FTDI_ADBUS[7]} FTDI_OEN FTDI_RDN FTDI_SIWU FTDI_TXN}]
set_output_delay -clock [get_clocks FTDI_CLK] -min 0.000 [get_ports {{FTDI_ADBUS[0]} {FTDI_ADBUS[1]} {FTDI_ADBUS[2]} {FTDI_ADBUS[3]} {FTDI_ADBUS[4]} {FTDI_ADBUS[5]} {FTDI_ADBUS[6]} {FTDI_ADBUS[7]} FTDI_OEN FTDI_RDN FTDI_SIWU FTDI_TXN}]

set_property IOSTANDARD LVCMOS33 [get_ports SHND_ADC_A]
set_property IOSTANDARD LVCMOS33 [get_ports SHND_ADC_B]
set_property IOSTANDARD LVCMOS33 [get_ports sw1]

set_property PACKAGE_PIN D12 [get_ports EECLK]
set_property PACKAGE_PIN D13 [get_ports EECS]
set_property PACKAGE_PIN G12 [get_ports EEMISO]
set_property PACKAGE_PIN E11 [get_ports EEMOSI]
set_property IOSTANDARD LVCMOS33 [get_ports EECLK]
set_property IOSTANDARD LVCMOS33 [get_ports EECS]
set_property IOSTANDARD LVCMOS33 [get_ports EEMISO]
set_property IOSTANDARD LVCMOS33 [get_ports EEMOSI]


set_false_path -from [get_clocks FTDI_CLK] -to [get_clocks -of_objects [get_pins mcg/inst/mmcm_adv_inst/CLKOUT0]]

# Oscilloscope_0 (U15) constraints

set_false_path -from [get_pins U15/READ_STATUS_reg[*]/C] -to [get_clocks -of_objects [get_pins U15/GENCH[*].xpm_memory_sdpram_inst/clkb]]
set_false_path -from [get_pins U15/READ_POSITION_reg[*]/C] -to [get_clocks -of_objects [get_pins U15/GENCH[*].xpm_memory_sdpram_inst/clkb]]
set_false_path -from [get_pins U15/BUSY_reg[*]/C] -to [get_clocks -of_objects [get_pins U15/GENCH[*].xpm_memory_sdpram_inst/clkb]]
set_false_path -from [get_pins -hierarchical -filter (NAME=~*/REG_Oscilloscope_0_*_WR_reg[*]/C)] -to [get_clocks -of_objects [get_pins U15/GENCH[*].xpm_memory_sdpram_inst/clka]]
